# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcfe3a88199d6949a9c611480e5caa030c1814c6ccde5d794cdd40492c004a2206e67884595568ac085d6a3febc635956d9de18c41197d91684c965a682ec317

test:
  secret_key_base: 5fe8535c531e3298743b5c303b9b78be76cedf2870e7c394fb9c0e013f5986e50859cbecdd1b3df87e922f77da19f9ede96a9f8fc20f894005ad74d8a78946c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
